// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package wrongt

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Case 1: nil testing.T passed to package-level assertions.
func TestWrongTChecker_NilT(t *testing.T) {
	var err error
	var result int

	assert.Equal(nil, 0, result)  // want "wrong-t: do not pass nil as testing\\.T"
	assert.NoError(nil, err)      // want "wrong-t: do not pass nil as testing\\.T"
	require.Equal(nil, 0, result) // want "wrong-t: do not pass nil as testing\\.T"
	require.NoError(nil, err)     // want "wrong-t: do not pass nil as testing\\.T"

	// Valid – using the test's t.
	assert.Equal(t, 0, result)
	assert.NoError(t, err)
	require.Equal(t, 0, result)
	require.NoError(t, err)

	t.Run("sub", func(t *testing.T) {
		assert.Equal(t, 0, result)
		require.NoError(t, err)
	})
}

// Case 2: freshly created testing.T passed to package-level assertions.
func TestWrongTChecker_FreshT(t *testing.T) {
	var err error
	var result int

	assert.Equal(&testing.T{}, 0, result)  // want "wrong-t: do not pass freshly created testing\\.T"
	assert.NoError(new(testing.T), err)    // want "wrong-t: do not pass freshly created testing\\.T"
	require.Equal(&testing.T{}, 0, result) // want "wrong-t: do not pass freshly created testing\\.T"
	require.NoError(new(testing.T), err)   // want "wrong-t: do not pass freshly created testing\\.T"

	u := &testing.T{}
	assert.Equal(u, 0, result)  // want "wrong-t: do not pass freshly created testing\\.T"
	require.Equal(u, 0, result) // want "wrong-t: do not pass freshly created testing\\.T"

	v := new(testing.T)
	assert.NoError(v, err)  // want "wrong-t: do not pass freshly created testing\\.T"
	require.NoError(v, err) // want "wrong-t: do not pass freshly created testing\\.T"

	// Valid – fresh variable reassigned to a real t before use.
	w := &testing.T{}
	w = t
	assert.Equal(w, 0, result)
	require.NoError(w, err)
}

// Case 3: assertion object created with outer t used inside t.Run subtest.
func TestWrongTChecker_Scope(t *testing.T) {
	a := assert.New(t)
	r := require.New(t)

	var err error
	var result int

	// Valid – used in same scope.
	a.Equal(0, result)
	r.NoError(err)

	cases := []struct{ Name string }{}
	for _, tc := range cases {
		t.Run(tc.Name, func(t *testing.T) {
			a.Equal(0, result) // want "wrong-t: assertion object a was created with outer scope's testing\\.T"
			r.NoError(err)     // want "wrong-t: assertion object r was created with outer scope's testing\\.T"

			// Valid – created inside this subtest.
			subA := assert.New(t)
			subA.Equal(0, result)
		})
	}

	t.Run("single", func(t *testing.T) {
		a.Equal(0, result) // want "wrong-t: assertion object a was created with outer scope's testing\\.T"

		// Nested subtest – a is still from outer scope.
		t.Run("nested", func(t *testing.T) {
			a.Equal(0, result) // want "wrong-t: assertion object a was created with outer scope's testing\\.T"

			// Valid – b is created inside this nested subtest.
			b := assert.New(t)
			b.Equal(0, result)
		})
	})

	// Rebound to outer t (not the callback's t): still an error because the
	// rebinding does not use the subtest's own t.
	outerT := t
	t.Run("rebind-wrong-t", func(t *testing.T) {
		a = assert.New(outerT)
		a.Equal(0, result) // want "wrong-t: assertion object a was created with outer scope's testing\\.T"
	})
}

// Valid uses: object-style calls (no t argument needed), or t from same scope.
func TestWrongTChecker_Valid(t *testing.T) {
	var err error
	var result int

	a := assert.New(t)
	r := require.New(t)

	a.Equal(0, result)
	r.NoError(err)

	t.Run("sub", func(t *testing.T) {
		assert.Equal(t, 0, result)
		require.NoError(t, err)

		inner := assert.New(t)
		inner.Equal(0, result)
	})

	// Valid – outer-scope assertion object rebound to subtest's t before use.
	t.Run("rebound", func(t *testing.T) {
		a = assert.New(t)
		r = require.New(t)
		a.Equal(0, result)
		r.NoError(err)
	})
}
