// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package gracefulteardown

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"
)

func TestGracefulTeardownChecker(t *testing.T) {
	var err error

	// OK: require in test body.
	require.NoError(t, err)

	// OK: assert in cleanup.
	t.Cleanup(func() {
		assert.NoError(t, err)
	})

	// Bad: require in cleanup.
	t.Cleanup(func() {
		require.NoError(t, err) // want "graceful-teardown: do not use require in cleanup code"
	})

	// Bad: multiple requires in cleanup.
	t.Cleanup(func() {
		require.NoError(t, err) // want "graceful-teardown: do not use require in cleanup code"
		require.Nil(t, err)     // want "graceful-teardown: do not use require in cleanup code"
	})
}

type GracefulTeardownCheckerSuite struct {
	suite.Suite
}

func TestGracefulTeardownCheckerSuite(t *testing.T) {
	suite.Run(t, new(GracefulTeardownCheckerSuite))
}

func (s *GracefulTeardownCheckerSuite) SetupTest() {
	// OK: require in setup.
	s.Require().NoError(nil)
}

func (s *GracefulTeardownCheckerSuite) TestSomething() {
	// OK: require in test method.
	s.Require().NoError(nil)
}

func (s *GracefulTeardownCheckerSuite) TearDownTest() {
	// OK: assert in teardown.
	s.Assert().NoError(nil)
	s.NoError(nil)

	// Bad: require in teardown.
	s.Require().NoError(nil) // want "graceful-teardown: do not use require in cleanup code"
}

func (s *GracefulTeardownCheckerSuite) TearDownSuite() {
	// Bad: require in teardown suite.
	s.Require().NoError(nil) // want "graceful-teardown: do not use require in cleanup code"
}

func (s *GracefulTeardownCheckerSuite) AfterTest(_, _ string) {
	// Bad: require in AfterTest.
	s.Require().NoError(nil) // want "graceful-teardown: do not use require in cleanup code"
}
