version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    update-types: semver-major
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
