run:
  tests: true

issues:
  max-same-issues: 0

  # revive should check comments for exported (and not internal) code.
  include: [ EXC0012, EXC0013, EXC0014 ]

  exclude-rules:
    - path: "internal/testgen"
      linters: [ "revive" ]
      text: "exported"

    - path: "internal"
      linters: [ "revive" ]
      text: "exported (method|const)"

    - source: "(Equalf?|NotEqualf?|Greaterf?|Lessf?|Truef?|Falsef?)"
      linters: [ "goconst" ]

    - path: "_test\\.go"
      linters: [ "lll" ]

linters-settings:
  depguard:
    rules:
      analysisutil:
        files: [ "**/internal/analysisutil/*.go" ]
        deny:
          - pkg: golang.org/x/tools/go/analysis
            desc: Please, implement helpers without usage of x/tools

  forbidigo:
    forbid:
      - p: types\.ExprString
        msg: Please, use analysisutil.NodeBytes/NodeString instead

  gocritic:
    disabled-checks:
      - singleCaseSwitch

  gosec:
    excludes:
      - "G306" # Expect WriteFile permissions to be 0600 or less

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Antonboom/testifylint)

  lll:
    line-length: 130

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - depguard
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
