version: "2"

run:
  tests: true

issues:
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gci:
      sections:
        - standard # A standard section: captures all standard packages.
        - default  # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/Antonboom/testifylint)

  exclusions:
    generated: lax
    paths:
      - internal/checkers/printf # A patched fork of go vet's printf.

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exptostd
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - path: "internal/testgen"
        linters: [ "revive" ]
        text: "exported"

      - path: "internal/testgen"
        linters: [ "forbidigo", "gochecknoinits", "prealloc" ] # Internal test generation tool.

      - path: "internal"
        linters: [ "revive" ]
        text: "exported (method|const)"

      - path: "_test\\.go"
        linters: [ "lll" ]

      - source: ' // want '
        linters: [ "lll" ]

    paths:
      - internal/checkers/printf # A patched fork of go vet's printf.

  settings:
    depguard:
      rules:
        analysisutil:
          files:
            - '**/internal/analysisutil/*.go'
          deny:
            - pkg: golang.org/x/tools/go/analysis
              desc: Please, implement helpers without usage of x/tools

    forbidigo:
      forbid:
        - pattern: panic
          msg: Please, don't panic

        - pattern: types\.ExprString
          msg: Please, use analysisutil.NodeBytes/NodeString instead

    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - paramTypeCombine
        - singleCaseSwitch
        - stringConcatSimplify
        - unnecessaryBlock
        - whyNoLint
        - yodaStyleExpr

    gosec:
      excludes:
        - G306 # Expect WriteFile permissions to be 0600 or less.

    govet:
      disable:
        - fieldalignment
      enable-all: true

    nolintlint:
      require-explanation: true
      allow-no-explanation: [ lll ]
      require-specific: true

    lll:
      line-length: 130

    revive:
      severity: error
      rules:
        - name: atomic
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: confusing-results
        - name: confusing-results
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redundant-build-tag
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-of-int
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unhandled-error
          arguments:
            - bytes.Buffer.Write
            - bytes.Buffer.WriteString
            - fmt.Fprint
            - fmt.Printf
            - fmt.Println
            - strings.Builder.WriteString
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: use-errors-new
        - name: useless-break
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
