run:
  tests: true

issues:
  max-same-issues: 0

  # revive should check comments for exported (and not internal) code.
  include: [ EXC0012, EXC0013, EXC0014 ]

  exclude-rules:
    - path: "internal/testgen"
      linters: [ "revive" ]
      text: "exported"

    - path: "internal"
      linters: [ "revive" ]
      text: "exported (method|const)"

    - source: "(Equalf?|NotEqualf?|Greaterf?|Lessf?|Truef?|Falsef?)"
      linters: [ "goconst" ]

    - path: "_test\\.go"
      linters: [ "lll" ]

linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch

  gosec:
    excludes:
      - "G306" # Expect WriteFile permissions to be 0600 or less

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Antonboom/testifylint)

  lll:
    line-length: 130

  tagliatelle:
    case:
      rules:
        yaml: kebab

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nestif
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
