enabled-checkers:
  - bool-compare
  - compares
  - empty
  - error
  - error-is
  - expected-actual
  - float-compare
  - len
  - require-error
  - suite-dont-use-pkg
  # - suite-no-extra-assert-call
  # - suite-thelper

expected-actual:
  # Pattern for expected variable name.
  exp-var-pattern: (^(exp(ected)?|want(ed)?)([A-Z]\w*)?$)|(^(\w*[a-z])?(Exp(ected)?|Want(ed)?)$)
