# https://taskfile.dev/#/installation
version: '3'

silent: true

vars:
  COVERED_PKGS: |
    ./analyzer
    ./internal/analysisutil
    ./internal/checkers
    ./internal/config

tasks:
  default:
    cmds:
      - task: tidy
      - task: lint
      - task: test
      - task: install

  tools:install:
    - echo "Install dev tools..."
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tidy:
    cmds:
      - echo "Tidy..."
      - go mod tidy

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run --fix ./...

  test:
    deps: [ test:gen ]
    cmds:
      - echo "Test..."
      - go test ./...

  test:coverage:
    cmds:
      - echo "Test with coverage..."
      - go test -coverpkg={{ .COVERED_PKGS | trim | splitLines | join "," }} -coverprofile=coverage.out ./...

  test:gen:
    cmds:
      - echo "Generate analyzer tests..."
      - go run ./internal/testgen

  profile:
    cmds:
      - echo "Do profiling..."
      - go test -memprofile=mem.out -cpuprofile=cpu.out ./analyzer

  install:
    cmds:
      - echo "Install..."
      - go install .
