# https://taskfile.dev/#/installation
version: '3'

silent: true

vars:
  CONFIG_EXAMPLE_PATH: .testifylint.yml

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests

  tools:install:
    - echo "Install local tools..."
    - go install github.com/daixiang0/gci@latest
    - go install mvdan.cc/gofumpt@latest

  tidy:
    cmds:
      - echo "Tidy..."
      - go mod tidy

  fmt:
    cmds:
      - echo "Fmt..."
      - gofumpt -w .
      - gci write -s standard -s default -s "Prefix(github.com/Antonboom/testifylint)" . 2> /dev/null

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run --fix ./...

  tests:
    cmds:
      - echo "Tests..."
      - go test ./...

  tests:coverage:
    cmds:
      - echo "Tests with coverage..."
      - go test -coverpkg ./analyzer,./config,./internal/analysisutil,./internal/checkers -coverprofile=coverage.out ./...

  tests:gen:
    cmds:
      - echo "Generate analyzer tests..."
      - go run ./internal/testgen

  install:
    cmds:
      - echo "Install..."
      - go install ./...
