// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package elementsmatch

import (
	"slices"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestElementsMatchChecker(t *testing.T) {
	var a, b []int

	// Invalid.
	{
		slices.Sort(a)
		slices.Sort(b)
		assert.True(t, slices.Equal(a, b)) // want "elements-match: use assert\\.ElementsMatch"

		slices.Sort(b)
		slices.Sort(a)
		assert.True(t, slices.Equal(a, b)) // want "elements-match: use assert\\.ElementsMatch"

		slices.Sort(a)
		slices.Sort(b)
		require.True(t, slices.Equal(a, b)) // want "elements-match: use require\\.ElementsMatch"

		slices.Sort(a)
		slices.Sort(b)
		assert.True(t, slices.Equal(a, b), "elements should match") // want "elements-match: use assert\\.ElementsMatch"

		slices.Sort(a)
		slices.Sort(b)
		assert.Truef(t, slices.Equal(a, b), "elements should match %d and %d", len(a), len(b)) // want "elements-match: use assert\\.ElementsMatchf"

		slices.Sort(a)
		slices.Sort(b)
		assert.True(t, slices.Equal(b, a)) // want "elements-match: use assert\\.ElementsMatch"
	}

	// Valid.
	{
		assert.ElementsMatch(t, a, b)

		// Only one sort call preceding assert.
		slices.Sort(a)
		assert.True(t, slices.Equal(a, b))

		// Sort args don't match Equal args.
		slices.Sort(a)
		slices.Sort(b)
		assert.True(t, slices.Equal(a, a))

		// Not a slices.Equal call.
		slices.Sort(a)
		slices.Sort(b)
		assert.True(t, a[0] == b[0])

		// Not assert.True.
		slices.Sort(a)
		slices.Sort(b)
		assert.Equal(t, a, b)
	}
}
