// Code generated by testifylint/internal/testgen. DO NOT EDIT.
package uselessimport

import "testing"
import _ "github.com/stretchr/testify"         // want "useless-import: avoid blank import of github.com/stretchr/testify as it does nothing"
import _ "github.com/stretchr/testify/assert"  // want "useless-import: avoid blank import of github.com/stretchr/testify/assert as it does nothing"
import _ "github.com/stretchr/testify/http"    // want "useless-import: avoid blank import of github.com/stretchr/testify/http as it does nothing"
import _ "github.com/stretchr/testify/mock"    // want "useless-import: avoid blank import of github.com/stretchr/testify/mock as it does nothing"
import _ "github.com/stretchr/testify/require" // want "useless-import: avoid blank import of github.com/stretchr/testify/require as it does nothing"
import _ "github.com/stretchr/testify/suite"   // want "useless-import: avoid blank import of github.com/stretchr/testify/suite as it does nothing"
import "strings"

import (
	_ "github.com/stretchr/testify"         // want "useless-import: avoid blank import of github.com/stretchr/testify as it does nothing"
	_ "github.com/stretchr/testify/assert"  // want "useless-import: avoid blank import of github.com/stretchr/testify/assert as it does nothing"
	_ "github.com/stretchr/testify/http"    // want "useless-import: avoid blank import of github.com/stretchr/testify/http as it does nothing"
	_ "github.com/stretchr/testify/mock"    // want "useless-import: avoid blank import of github.com/stretchr/testify/mock as it does nothing"
	_ "github.com/stretchr/testify/require" // want "useless-import: avoid blank import of github.com/stretchr/testify/require as it does nothing"
	_ "github.com/stretchr/testify/suite"   // want "useless-import: avoid blank import of github.com/stretchr/testify/suite as it does nothing"
)

import (
	_ "gopkg.in/yaml.v3"
	"net/url"
	// Testing.

	_ "github.com/stretchr/testify"         // want "useless-import: avoid blank import of github.com/stretchr/testify as it does nothing"
	_ "github.com/stretchr/testify/assert"  // want "useless-import: avoid blank import of github.com/stretchr/testify/assert as it does nothing"
	_ "github.com/stretchr/testify/http"    // want "useless-import: avoid blank import of github.com/stretchr/testify/http as it does nothing"
	_ "github.com/stretchr/testify/mock"    // want "useless-import: avoid blank import of github.com/stretchr/testify/mock as it does nothing"
	_ "github.com/stretchr/testify/require" // want "useless-import: avoid blank import of github.com/stretchr/testify/require as it does nothing"
	_ "github.com/stretchr/testify/suite"   // want "useless-import: avoid blank import of github.com/stretchr/testify/suite as it does nothing"

	. "database/sql"
	_ "github.com/pmezard/go-difflib/difflib"
)

func TestDummy(t *testing.T) {
	dummy := 1 + 3
	if dummy != 4 {
		t.Errorf("expected %d, but got %d", 4, dummy)
	}

	_ = strings.Builder{}
	_ = url.URL{}
	_ = DB{}
}
