package main

import "text/template"

type LenCasesGenerator struct{}

func (g LenCasesGenerator) Template() *template.Template {
	return lenCasesTmpl
}

func (g LenCasesGenerator) Data() any {
	return struct {
		Pkgs    []string
		LenVars []any

		VarSets           [][]any
		InvalidChecks     []Check
		ValidChecks       []Check
		ValidLenLenChecks []Check
	}{
		Pkgs: []string{"assert", "require"},
		VarSets: [][]any{
			{"a"}, {"b.i"}, {"c"}, {"d"}, {"*e"}, {"f.Count()"}, {"intOp()"},
		},
		InvalidChecks: []Check{
			{Fn: "Equal", ArgsTmpl: "t, len(arr), %s", ReportedMsg: "use %s.Len"},
			{Fn: "Equal", ArgsTmpl: "t, %s, len(arr)", ReportedMsg: "use %s.Len"},
			{Fn: "True", ArgsTmpl: "t, len(arr) == %s", ReportedMsg: "use %s.Len"},
			{Fn: "True", ArgsTmpl: "t, %s == len(arr)", ReportedMsg: "use %s.Len"},
		},
		ValidChecks: []Check{
			{Fn: "Len", ArgsTmpl: "t, arr, %s"},

			{Fn: "NotEqual", ArgsTmpl: "t, len(arr), %s"},
			{Fn: "NotEqual", ArgsTmpl: "t, %s, len(arr)"},
			{Fn: "Greater", ArgsTmpl: "t, len(arr), %s"},
			{Fn: "Greater", ArgsTmpl: "t, %s, len(arr)"},
			{Fn: "GreaterOrEqual", ArgsTmpl: "t, len(arr), %s"},
			{Fn: "GreaterOrEqual", ArgsTmpl: "t, %s, len(arr)"},
			{Fn: "Less", ArgsTmpl: "t, len(arr), %s"},
			{Fn: "Less", ArgsTmpl: "t, %s, len(arr)"},
			{Fn: "LessOrEqual", ArgsTmpl: "t, len(arr), %s"},
			{Fn: "LessOrEqual", ArgsTmpl: "t, %s, len(arr)"},

			{Fn: "True", ArgsTmpl: "t, len(arr) != %s"},
			{Fn: "True", ArgsTmpl: "t, %s != len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) > %s"},
			{Fn: "True", ArgsTmpl: "t, %s > len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) >= %s"},
			{Fn: "True", ArgsTmpl: "t, %s >= len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) < %s"},
			{Fn: "True", ArgsTmpl: "t, %s < len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) <= %s"},
			{Fn: "True", ArgsTmpl: "t, %s <= len(arr)"},

			{Fn: "False", ArgsTmpl: "t, len(arr) != %s"},
			{Fn: "False", ArgsTmpl: "t, %s != len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) > %s"},
			{Fn: "False", ArgsTmpl: "t, %s > len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) >= %s"},
			{Fn: "False", ArgsTmpl: "t, %s >= len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) < %s"},
			{Fn: "False", ArgsTmpl: "t, %s < len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) <= %s"},
			{Fn: "False", ArgsTmpl: "t, %s <= len(arr)"},
		},
		ValidLenLenChecks: []Check{
			{Fn: "Equal", ArgsTmpl: "t, len(arr), len(arr)"},
			{Fn: "NotEqual", ArgsTmpl: "t, len(arr), len(arr)"},
			{Fn: "Greater", ArgsTmpl: "t, len(arr), len(arr)"},
			{Fn: "GreaterOrEqual", ArgsTmpl: "t, len(arr), len(arr)"},
			{Fn: "Less", ArgsTmpl: "t, len(arr), len(arr)"},
			{Fn: "LessOrEqual", ArgsTmpl: "t, len(arr), len(arr)"},

			{Fn: "True", ArgsTmpl: "t, len(arr) == len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) != len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) > len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) >= len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) < len(arr)"},
			{Fn: "True", ArgsTmpl: "t, len(arr) <= len(arr)"},

			{Fn: "False", ArgsTmpl: "t, len(arr) == len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) != len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) > len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) >= len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) < len(arr)"},
			{Fn: "False", ArgsTmpl: "t, len(arr) <= len(arr)"},
		},
	}
}

var lenCasesTmpl = template.Must(template.New("lenCasesTmpl").
	Funcs(template.FuncMap{
		"ExpandCheck": ExpandCheck,
	}).
	Parse(`// Code generated by testifylint/internal/cmd/testgen. DO NOT EDIT.

package basic

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLen(t *testing.T) {
	type withInt struct{ i int }
	intOp := func() int { return 42 }

	var a int
	var b withInt
	c := 1
	const d = 2
	e := new(int)
	var f withIntMethod

	arr := [...]int{1, 2, 3}
	{{ range $pi, $pkg := .Pkgs }}
	t.Run("{{ $pkg }}", func(t *testing.T) {
		{{- range $vi, $vars := $.VarSets }}
		{
			{{- range $ci, $check := $.InvalidChecks }}
			{{ ExpandCheck $check $pkg $vars }}
			{{ end }}}
		{{ end }}
		// Valid {{ $pkg }}s.
		{{- range $vi, $vars := $.VarSets }}
		{
			{{- range $ci, $check := $.ValidChecks }}
			{{ ExpandCheck $check $pkg $vars }}
			{{ end }}}
		{{ end }}
		{
		{{- range $ci, $check := $.ValidLenLenChecks }}
			{{ ExpandCheck $check $pkg nil }}
		{{ end }}}
	})
	{{ end }}}

type withIntMethod struct{}

func (withIntMethod) Count() int { return 1 }
`))
