// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package timecompare

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func TestTimeCompareChecker(t *testing.T) {
	var t1, t2, zeroTime time.Time
	d := time.Now()
	now := time.Now()
	expectedTime, expiryTime := time.Now(), time.Now()
	token := expiringToken{Expiry: time.Now()}
	alert := alert{Updated: time.Now()}
	cc := container{firstDetected: time.Now()}

	// Invalid.
	{
		assert.Equal(t, time.Now(), t1)                                                   // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equalf(t, time.Now(), t1, "msg with args %d %s", 42, "42")                 // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equal(t, alert.Updated, time.Now())                                        // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equalf(t, alert.Updated, time.Now(), "msg with args %d %s", 42, "42")      // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.EqualValues(t, time.Now(), t1)                                             // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.EqualValuesf(t, time.Now(), t1, "msg with args %d %s", 42, "42")           // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.EqualValues(t, t1, time.Now())                                             // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.EqualValuesf(t, t1, time.Now(), "msg with args %d %s", 42, "42")           // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Exactly(t, time.Now(), cc.firstDetected)                                   // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Exactlyf(t, time.Now(), cc.firstDetected, "msg with args %d %s", 42, "42") // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Exactly(t, t1, time.Now())                                                 // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Exactlyf(t, t1, time.Now(), "msg with args %d %s", 42, "42")               // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqual(t, time.Now(), t1)                                                // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualf(t, time.Now(), t1, "msg with args %d %s", 42, "42")              // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqual(t, t1, time.Now())                                                // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualf(t, t1, time.Now(), "msg with args %d %s", 42, "42")              // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualValues(t, time.Now(), t1)                                          // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualValuesf(t, time.Now(), t1, "msg with args %d %s", 42, "42")        // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualValues(t, t1, time.Now())                                          // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualValuesf(t, t1, time.Now(), "msg with args %d %s", 42, "42")        // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equal(t, time.Time{}, t1)                                                  // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equalf(t, time.Time{}, t1, "msg with args %d %s", 42, "42")                // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equal(t, t1, time.Time{})                                                  // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.Equalf(t, t1, time.Time{}, "msg with args %d %s", 42, "42")                // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqual(t, time.Time{}, t1)                                               // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualf(t, time.Time{}, t1, "msg with args %d %s", 42, "42")             // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqual(t, t1, time.Time{})                                               // want "time-compare: equality-based assertion on time\\.Time can be flaky"
		assert.NotEqualf(t, t1, time.Time{}, "msg with args %d %s", 42, "42")             // want "time-compare: equality-based assertion on time\\.Time can be flaky"
	}

	// Valid.
	{
		assert.True(t, t1.Equal(t2))
		assert.Truef(t, t1.Equal(t2), "msg with args %d %s", 42, "42")
		assert.False(t, t1.Equal(t2))
		assert.Falsef(t, t1.Equal(t2), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.Unix(), t2.Unix())
		assert.Equalf(t, t1.Unix(), t2.Unix(), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.UnixMilli(), t2.UnixMilli())
		assert.Equalf(t, t1.UnixMilli(), t2.UnixMilli(), "msg with args %d %s", 42, "42")
		assert.EqualValues(t, t1.UnixMicro(), t2.UnixMicro())
		assert.EqualValuesf(t, t1.UnixMicro(), t2.UnixMicro(), "msg with args %d %s", 42, "42")
		assert.Exactly(t, t1.UnixNano(), t2.UnixNano())
		assert.Exactlyf(t, t1.UnixNano(), t2.UnixNano(), "msg with args %d %s", 42, "42")
		assert.WithinDuration(t, t1, t2, 0)
		assert.WithinDurationf(t, t1, t2, 0, "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.Truncate(0), t2.Round(0))
		assert.Equalf(t, t1.Truncate(0), t2.Round(0), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.UTC(), t2.UTC())
		assert.Equalf(t, t1.UTC(), t2.UTC(), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.Local(), t2.Local())
		assert.Equalf(t, t1.Local(), t2.Local(), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.In(time.UTC), t2.In(time.UTC))
		assert.Equalf(t, t1.In(time.UTC), t2.In(time.UTC), "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.Add(time.Second), t2.Add(time.Second))
		assert.Equalf(t, t1.Add(time.Second), t2.Add(time.Second), "msg with args %d %s", 42, "42")
		assert.Equal(t, zeroTime.Add(time.Second), t1)
		assert.Equalf(t, zeroTime.Add(time.Second), t1, "msg with args %d %s", 42, "42")
		assert.Equal(t, t1.AddDate(0, 0, 1), t2.AddDate(0, 0, 1))
		assert.Equalf(t, t1.AddDate(0, 0, 1), t2.AddDate(0, 0, 1), "msg with args %d %s", 42, "42")
		assert.Equal(t, time.Date(2017, time.January, 24, 0, 0, 0, 0, time.UTC), d)
		assert.Equalf(t, time.Date(2017, time.January, 24, 0, 0, 0, 0, time.UTC), d, "msg with args %d %s", 42, "42")
		assert.True(t, t1.IsZero())
		assert.Truef(t, t1.IsZero(), "msg with args %d %s", 42, "42")
		assert.False(t, now.IsZero())
		assert.Falsef(t, now.IsZero(), "msg with args %d %s", 42, "42")
		assert.Zero(t, t2)
		assert.Zerof(t, t2, "msg with args %d %s", 42, "42")
		assert.NotZero(t, now)
		assert.NotZerof(t, now, "msg with args %d %s", 42, "42")
		assert.Equal(t, time.Duration(0), expectedTime.Round(time.Second).Sub(expiryTime.Round(time.Second)))
		assert.Equalf(t, time.Duration(0), expectedTime.Round(time.Second).Sub(expiryTime.Round(time.Second)), "msg with args %d %s", 42, "42")
		assert.Equal(t, 5*time.Minute, time.Until(token.Expiry).Round(time.Second))
		assert.Equalf(t, 5*time.Minute, time.Until(token.Expiry).Round(time.Second), "msg with args %d %s", 42, "42")
		assert.Equal(t, 0, t1.Compare(t2))
		assert.Equalf(t, 0, t1.Compare(t2), "msg with args %d %s", 42, "42")
		assert.True(t, t1.Compare(t2) == 0)
		assert.Truef(t, t1.Compare(t2) == 0, "msg with args %d %s", 42, "42")
		assert.False(t, t1.Compare(t2) != 0)
		assert.Falsef(t, t1.Compare(t2) != 0, "msg with args %d %s", 42, "42")
		assert.EqualExportedValues(t, metric{Value: 100, t: t1}, metric{Value: 100, t: t2})
		assert.EqualExportedValuesf(t, metric{Value: 100, t: t1}, metric{Value: 100, t: t2}, "msg with args %d %s", 42, "42")
	}
}

type alert struct {
	Updated time.Time
}

type container struct {
	firstDetected time.Time
}

type expiringToken struct {
	Expiry time.Time
}

type metric struct {
	Value int
	t     time.Time
}
