// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package httpmultiple

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func handler(w http.ResponseWriter, r *http.Request) {}

func TestHttpMultipleChecker(t *testing.T) {
	// Invalid: multiple HTTP assertions with the same handler and args.
	assert.HTTPStatusCode(t, handler, "GET", "/index", nil, http.StatusOK) // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	assert.HTTPBodyContains(t, handler, "GET", "/index", nil, "hello")     // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"

	assert.HTTPError(t, handler, "GET", "/error", nil)                // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	assert.HTTPBodyContains(t, handler, "GET", "/error", nil, "oops") // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"

	require.HTTPRedirect(t, handler, "GET", "/redirect", nil)                     // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	require.HTTPStatusCode(t, handler, "GET", "/redirect", nil, http.StatusFound) // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"

	// Invalid: formatted (*f) variants are also detected.
	assert.HTTPStatusCodef(t, handler, "GET", "/fmt", nil, http.StatusOK, "msg") // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	assert.HTTPBodyContainsf(t, handler, "GET", "/fmt", nil, "hello", "msg")     // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"

	// Invalid: non-nil url.Values query parameters.
	assert.HTTPStatusCode(t, handler, "GET", "/search", url.Values{"q": {"go"}}, http.StatusOK) // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	assert.HTTPBodyContains(t, handler, "GET", "/search", url.Values{"q": {"go"}}, "result")    // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"

	// Valid: single HTTP assertion.
	assert.HTTPStatusCode(t, handler, "GET", "/single", nil, http.StatusOK)

	// Valid: different handlers.
	assert.HTTPSuccess(t, handler, "GET", "/a", nil)
	assert.HTTPSuccess(t, http.NotFound, "GET", "/a", nil)

	// Valid: different methods.
	assert.HTTPSuccess(t, handler, "GET", "/b", nil)
	assert.HTTPSuccess(t, handler, "POST", "/b", nil)

	// Valid: different URLs.
	assert.HTTPSuccess(t, handler, "GET", "/c", nil)
	assert.HTTPSuccess(t, handler, "GET", "/d", nil)

	// Valid: same-key assertions in separate closures are independent scopes.
	t.Run("sub1", func(t *testing.T) {
		assert.HTTPStatusCode(t, handler, "GET", "/subtest", nil, http.StatusOK)
	})
	t.Run("sub2", func(t *testing.T) {
		assert.HTTPBodyContains(t, handler, "GET", "/subtest", nil, "hello")
	})

	// Valid: goroutine closure is an independent scope.
	go func() {
		assert.HTTPStatusCode(t, handler, "GET", "/goroutine", nil, http.StatusOK)
	}()
	go func() {
		assert.HTTPBodyContains(t, handler, "GET", "/goroutine", nil, "hello")
	}()

	// Valid: using httptest directly (the recommended approach).
	req := httptest.NewRequestWithContext(t.Context(), "GET", "/direct", nil)
	rr := httptest.NewRecorder()
	handler(rr, req)
	assert.Equal(t, http.StatusOK, rr.Code)
}

// TestHttpMultipleCheckerTT uses a non-"t" TestingT variable to verify the fix
// extracts the actual identifier from the call rather than hard-coding "t".
func TestHttpMultipleCheckerTT(tt *testing.T) {
	assert.HTTPStatusCode(tt, handler, "GET", "/tt-path", nil, http.StatusOK) // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
	assert.HTTPBodyContains(tt, handler, "GET", "/tt-path", nil, "hello")     // want "http-multiple: use httptest\\.NewRecorder\\(\\) instead of multiple HTTP assertions for the same handler call"
}
