// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package zero

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func TestZeroChecker(t *testing.T) {
	var ts, zeroTime time.Time

	// Invalid.
	{
		assert.Equal(t, zeroTime, ts)                                               // want "zero: use assert\\.Zero"
		assert.Equalf(t, zeroTime, ts, "msg with args %d %s", 42, "42")             // want "zero: use assert\\.Zerof"
		assert.Equal(t, time.Time{}, ts)                                            // want "zero: use assert\\.Zero"
		assert.Equalf(t, time.Time{}, ts, "msg with args %d %s", 42, "42")          // want "zero: use assert\\.Zerof"
		assert.EqualValues(t, zeroTime, ts)                                         // want "zero: use assert\\.Zero"
		assert.EqualValuesf(t, zeroTime, ts, "msg with args %d %s", 42, "42")       // want "zero: use assert\\.Zerof"
		assert.EqualValues(t, time.Time{}, ts)                                      // want "zero: use assert\\.Zero"
		assert.EqualValuesf(t, time.Time{}, ts, "msg with args %d %s", 42, "42")    // want "zero: use assert\\.Zerof"
		assert.Exactly(t, zeroTime, ts)                                             // want "zero: use assert\\.Zero"
		assert.Exactlyf(t, zeroTime, ts, "msg with args %d %s", 42, "42")           // want "zero: use assert\\.Zerof"
		assert.Exactly(t, time.Time{}, ts)                                          // want "zero: use assert\\.Zero"
		assert.Exactlyf(t, time.Time{}, ts, "msg with args %d %s", 42, "42")        // want "zero: use assert\\.Zerof"
		assert.True(t, zeroTime.IsZero())                                           // want "zero: use assert\\.Zero"
		assert.Truef(t, zeroTime.IsZero(), "msg with args %d %s", 42, "42")         // want "zero: use assert\\.Zerof"
		assert.True(t, time.Time{}.IsZero())                                        // want "zero: use assert\\.Zero"
		assert.Truef(t, time.Time{}.IsZero(), "msg with args %d %s", 42, "42")      // want "zero: use assert\\.Zerof"
		assert.True(t, ts.Equal(zeroTime))                                          // want "zero: use assert\\.Zero"
		assert.Truef(t, ts.Equal(zeroTime), "msg with args %d %s", 42, "42")        // want "zero: use assert\\.Zerof"
		assert.True(t, ts.Equal(time.Time{}))                                       // want "zero: use assert\\.Zero"
		assert.Truef(t, ts.Equal(time.Time{}), "msg with args %d %s", 42, "42")     // want "zero: use assert\\.Zerof"
		assert.NotEqual(t, zeroTime, ts)                                            // want "zero: use assert\\.NotZero"
		assert.NotEqualf(t, zeroTime, ts, "msg with args %d %s", 42, "42")          // want "zero: use assert\\.NotZerof"
		assert.NotEqual(t, time.Time{}, ts)                                         // want "zero: use assert\\.NotZero"
		assert.NotEqualf(t, time.Time{}, ts, "msg with args %d %s", 42, "42")       // want "zero: use assert\\.NotZerof"
		assert.NotEqualValues(t, zeroTime, ts)                                      // want "zero: use assert\\.NotZero"
		assert.NotEqualValuesf(t, zeroTime, ts, "msg with args %d %s", 42, "42")    // want "zero: use assert\\.NotZerof"
		assert.NotEqualValues(t, time.Time{}, ts)                                   // want "zero: use assert\\.NotZero"
		assert.NotEqualValuesf(t, time.Time{}, ts, "msg with args %d %s", 42, "42") // want "zero: use assert\\.NotZerof"
		assert.False(t, zeroTime.IsZero())                                          // want "zero: use assert\\.NotZero"
		assert.Falsef(t, zeroTime.IsZero(), "msg with args %d %s", 42, "42")        // want "zero: use assert\\.NotZerof"
		assert.False(t, time.Time{}.IsZero())                                       // want "zero: use assert\\.NotZero"
		assert.Falsef(t, time.Time{}.IsZero(), "msg with args %d %s", 42, "42")     // want "zero: use assert\\.NotZerof"
		assert.False(t, ts.Equal(zeroTime))                                         // want "zero: use assert\\.NotZero"
		assert.Falsef(t, ts.Equal(zeroTime), "msg with args %d %s", 42, "42")       // want "zero: use assert\\.NotZerof"
		assert.False(t, ts.Equal(time.Time{}))                                      // want "zero: use assert\\.NotZero"
		assert.Falsef(t, ts.Equal(time.Time{}), "msg with args %d %s", 42, "42")    // want "zero: use assert\\.NotZerof"
	}

	// Valid.
	{
		assert.Zero(t, ts)
		assert.Zerof(t, ts, "msg with args %d %s", 42, "42")
		assert.NotZero(t, ts)
		assert.NotZerof(t, ts, "msg with args %d %s", 42, "42")
		assert.Equal(t, 0, ts.Compare(zeroTime))
		assert.Equalf(t, 0, ts.Compare(zeroTime), "msg with args %d %s", 42, "42")
		assert.EqualValues(t, 0, ts.Compare(zeroTime))
		assert.EqualValuesf(t, 0, ts.Compare(zeroTime), "msg with args %d %s", 42, "42")
		assert.Exactly(t, 0, ts.Compare(zeroTime))
		assert.Exactlyf(t, 0, ts.Compare(zeroTime), "msg with args %d %s", 42, "42")
		assert.NotEqual(t, 0, ts.Compare(time.Time{}))
		assert.NotEqualf(t, 0, ts.Compare(time.Time{}), "msg with args %d %s", 42, "42")
		assert.NotEqualValues(t, 0, ts.Compare(time.Time{}))
		assert.NotEqualValuesf(t, 0, ts.Compare(time.Time{}), "msg with args %d %s", 42, "42")
		assert.Equal(t, zeroTime.Add(time.Second), ts)
		assert.Equalf(t, zeroTime.Add(time.Second), ts, "msg with args %d %s", 42, "42")
	}
}
